[WIP] #9 Get Data for Popular Screen: Logs the data for both screens
pmiclynx/summerPractice-2022 pull request #23
Opened 2022-07-15 10:00 UTC by DomiSzocs

2022-07-15 10:20 UTC, pmiclynx requested changes

2022-07-15 10:20 UTC, pmiclynx commented on app/src/main/java/com/summer/practice/tvtracker/networking/Movies.kt
> +data class Movies(
Let's rename it into Movie since this is the data for one movie only

2022-07-15 10:20 UTC, pmiclynx commented on app/src/main/java/com/summer/practice/tvtracker/networking/Api.kt
> +
I would recommend to add here the baseUrl for image as well

2022-07-15 10:20 UTC, pmiclynx commented on app/src/main/java/com/summer/practice/tvtracker/TopRatedFragment.kt
> +        }
duplicate code, let's extract the "data manipulation" into a single method that just returns to us a list where the full image url was set

2022-07-15 10:20 UTC, pmiclynx commented on app/src/main/java/com/summer/practice/tvtracker/networking/Api.kt
> +const val apiKey = "0a416fc6c49f4a04db6e3bd398ef8579"
if you want something challenging, you can get rid of the apiKey param in those GET methods and add it to retrofit interceptor

2022-07-15 10:20 UTC, pmiclynx commented on app/src/main/java/com/summer/practice/tvtracker/networking/MoviesRepository.kt
> +                onError.invoke("Empty response body")
duplicate code, only the getTopRatedList & getPopularList call is changed, the rest of them is the same code, please find a way to get rid of the code duplication

2022-07-15 12:12 UTC, DomiSzocs commented
Oopsie, I thought this won't be reviewed, since I used the [WIP] tag, I only fixed the Code duplications, but i'll take a look at the rest aswell :)

2022-07-15 13:52 UTC, pmiclynx requested changes

2022-07-15 13:52 UTC, pmiclynx commented on app/src/main/java/com/summer/practice/tvtracker/networking/CreateCallbackObject.kt
> +    fun createObject() = object: Callback<Results> {
remove the class and leave only the createObject method, add the onSuccess and onError params to this method. Let's have a final version like this:
```
fun createCallback(
        onSuccess: (List<Movies>) ->Unit,
        onError: (String)->Unit
) {
   // object: Callback<Result>...
}
````

2022-07-19 05:36 UTC, pmiclynx commented
I can review in each state, I just want to make sure you're on the right path, gj so far

2022-07-20 13:12 UTC, pmiclynx approved these changes

2022-07-20 13:25 UTC, abalazsilynx approved these changes

2022-07-20 13:26 UTC, closed without merging