Make login and register with firebase #8
pmiclynx/summerPractice-2022 pull request #27
Opened 2022-07-19 11:03 UTC by zsombics

2022-07-19 11:43 UTC, pmiclynx commented
A few behaviors are not correct:
- creating an account with success then pressing back from MainActivity redirects the user to login screen. The correct behavior should be: not redirecting the user to the login screen after a successful registration/login
- In case the user did a successful login/register it should be kept logged inside the app. Please read again the issue description from here: https://github.com/pmiclynx/summerPractice-2022/issues/8
![image](https://user-images.githubusercontent.com/88314300/179741513-ef21aa71-3a05-4e46-8e92-1a5eb1ee7af3.png)

 This behavior should be tested as following:
1. open the app without a logged user
2. make login/register
3. close the app
4. open the app again

The user should be navigated to the MainActivity and not to login screen again

The user logged/not logged navigation has to be handled in the SplashActivity.

2022-07-19 11:47 UTC, pmiclynx requested changes
Please re-check the app behavior

2022-07-20 11:08 UTC, pmiclynx approved these changes

2022-07-20 12:26 UTC, tnorbertlynx approved these changes

2022-07-20 12:29 UTC, merged